[package]
name = "streambed-test"
version = "0.1.0"
edition = "2021"

[dependencies]
http = { workspace = true }
hyper = { workspace = true, default-features = false, features = ["tcp", "stream", "http1", "http2", "client", "server", "runtime"] }
tokio = { workspace = true, features = ["full"] }
