name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: |
        rustup update
    - uses: Swatinem/rust-cache@v2
          
    - name: Format, lint and test
      run: |
        cargo fmt -- --check
        cargo clippy --verbose
        cargo test --verbose
